### ISSUE TITLE
Unresponsive Media Notification

### ISSUE THREAD

**Issue by intermarc** [dharmaseed/dharmaseed-android#101]
The media notification of the app sometimes becomes unresponsive when the app is closed in the background (by the user or the system). This bug affects both the current production release 1.6.2 (96542d0511f25acea9d184add75ee574dd31c4fa) and the branch `playback_resumption` (9393e42556695ab77c956b86f7484308e437aef9).

The issue is complicated because it appears to affect different API levels differently. Details follow in the comments below.

**Comment by intermarc** [comment]
In v1.6.2 (96542d0511f25acea9d184add75ee574dd31c4fa), the broken media notification affects API level 34 as illustrated in this video captured from the emulator in Android Studio:

https://github.com/dharmaseed/dharmaseed-android/assets/144038206/0ba36db1-956d-4c45-81f8-800af92d88ad

By contrast, API levels 30 and 33 do not seem to be affected. In these cases, the work-around of commit c98006402056faaca9880c7b21f7fe86f4535c8c does what it should: the MediaSessionService is stopped when the app stops such that we aren't left with a broken notification. Here is another video captured from the emulator with API level 33:

https://github.com/dharmaseed/dharmaseed-android/assets/144038206/88fa5025-cb27-485a-ae87-142ef46e7e48

**Comment by intermarc** [comment]
The branch `playback_resumption` implements changes that should make this work-around unnecessary. It implements the playback resumption feature described [here](https://developer.android.com/media/media3/session/background-playback#resumption).

> Media3 includes an API to enable users to resume playback after an app has terminated and even after the device has been restarted. 

I haven't been able to get this new feature to work yet, though.

On API level 34, the behavior is the same as in the `v1.6.2` release:

https://github.com/dharmaseed/dharmaseed-android/assets/144038206/8b371d90-021a-483b-a07e-65df80b51d51

 The `mediaserver` logs show the following error when the play button of the notification is pressed:

`2024-04-21 10:31:19.983   444-5428  mediaserver             mediaserver                          E  unlinkToDeath: removed reference to death recipient but unlink failed: DEAD_OBJECT
2024-04-21 10:31:20.009   444-1023  ResourceManagerMetrics  mediaserver                          I  pushConcurrentUsageReport: No Video Codec Entry for Application[pid(2083): uid(10185)]
2024-04-21 10:31:20.010   444-1023  ResourceManagerMetrics  mediaserver                          I  pushConcurrentUsageReport: Concurrent Codec Usage Report for the Process[pid(2083): uid(10185)] is Peak { AudioDec[ SW: 1 ] } Peak Pixels: 0
2024-04-21 10:31:20.018   444-5428  IPCThreadState          mediaserver                          E  attemptIncStrongHandle(3): Not supported
`

This seems to be a [known issue](https://github.com/androidx/media/issues/805) with API level 34.

**Comment by intermarc** [comment]
In API level 33, the behavior is the same as in API level 34, but I can't find any error messages in the log.

**Comment by intermarc** [comment]
In API level 30,  behavior of the `playback_resumption` branch is the same as in API levels 33 and 34. The app log shows the following error:

> 2024-04-21 10:56:30.876  7535-7535  PlaybackService         org.dharmaseed.android               D  entered onPlaybackResumption
> 2024-04-21 10:56:39.317  7535-7535  PlaybackService         org.dharmaseed.android               D  entered onPlaybackResumption
> 2024-04-21 10:56:40.652  7535-7535  ExoPlayerImpl           org.dharmaseed.android               I  Release 5ea3391 [AndroidXMedia3/1.3.0] [generic_x86_arm, sdk_gphone_x86, Google, 30] [media3.common, media3.exoplayer, media3.decoder, media3.session]
> --------- beginning of crash
> 2024-04-21 10:56:40.659  7535-7535  AndroidRuntime          org.dharmaseed.android               D  Shutting down VM
> 2024-04-21 10:56:40.663  7535-7535  AndroidRuntime          org.dharmaseed.android               E  FATAL EXCEPTION: main
>                                                                                                     Process: org.dharmaseed.android, PID: 7535
>                                                                                                     android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9193584 u0 org.dharmaseed.android/.PlaybackService}
>                                                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                                                     	at android.os.Looper.loop(Looper.java:223)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:7656)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
