### ISSUE TITLE
New talks won't play after update from asset DB

### ISSUE THREAD

**Issue by intermarc** [dharmaseed/dharmaseed-android#93]
We recently added new functionality to update the DBs of existing users with tables from the DB bundled with the app when it is updated (see [PR 90](https://github.com/dharmaseed/dharmaseed-android/pull/90)).

Unfortunately, something seems to be going wrong after existing tables are replaced with tables from the asset DB in this way (in `DBManager::onUpgrade`). Although the tables are updated as they should be and talks from the updated tables can be played etc., any talks that are added in a regular refresh thereafter cannot be played. Instead, selecting one of the newly added talks crashes the App with the following error message:

`FATAL EXCEPTION: main
Process: org.dharmaseed.android, PID: 4690
java.lang.RuntimeException: Unable to resume activity {org.dharmaseed.android/org.dharmaseed.android.PlayTalkActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4962)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4995)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at org.dharmaseed.android.Talk.isDownloaded(Talk.java:130)
at org.dharmaseed.android.PlayTalkActivity.toggleDownloadImage(PlayTalkActivity.java:494)
at org.dharmaseed.android.PlayTalkActivity.onResume(PlayTalkActivity.java:177)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
at android.app.Activity.performResume(Activity.java:8743)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4952)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4995) 
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57) 
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:205) 
at android.os.Looper.loop(Looper.java:294) 
at android.app.ActivityThread.main(ActivityThread.java:8177) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) ` 

Steps to reproduce:
1. Revert the App to an older version, before DB v3 was introduced (e.g. commit ID 49c41d24d69d10d3d7f3e5a248294edc5a3f601d). This will require a re-install which also inserts an old version of the DB.
2. Update the App to the head of the current master branch
3. Tap or click the newest talk
4. App crashes with the above error instead of showing the talk detail page

A fresh install of the App, which just starts with a copy of the most recent asset DB, does not have this issue. The problem is therefore related to the way tables are transferred in `DBManager::onUpgrade`.

What a mess! The likely reason why this issue did not show up during testing for PR90 is that it only affects new items. At the time of the PR, however, the new asset DB was basically up to date and there were no or just a few new talks that would have triggered the problem.

**Comment by bb4242** [comment]
I verified that #94 fixes the issue, thanks @intermarc!
