### ISSUE TITLE
Attempting to play a downloaded talk with a "?" in the title fails

### ISSUE THREAD

**Issue by bb4242** [dharmaseed/dharmaseed-android#97]
Steps to reproduce:

1) Find a talk with a literal question mark (?) in the title, such as https://dharmaseed.org/talks/81433/
2) Download the talk and wait for the download to complete
3) Attempt to play the talk. This will fail with the following stack trace:

```
Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:701)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:673)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                          at android.os.Looper.loop(Looper.java:294)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.datasource.FileDataSource$FileDataSourceException: uri has query and/or fragment, which are not supported. Did you call Uri.parse() on a string containing '?' or '#'? Use Uri.fromFile(new File(path)) to avoid this. path=/data/user/0/org.dharmaseed.android/files/downloads/ds_81433_What is Equanimity Anyway,query= And Is It Worth Cultivating? (Retreat at Spirit Rock).mp3,fragment=null
                                                                                                          at androidx.media3.datasource.FileDataSource.openLocalFile(FileDataSource.java:190)
                                                                                                          at androidx.media3.datasource.FileDataSource.open(FileDataSource.java:116)
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:417)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                      Caused by: java.io.FileNotFoundException: /data/user/0/org.dharmaseed.android/files/downloads/ds_81433_What is Equanimity Anyway: open failed: ENOENT (No such file or directory)
                                                                                                          at libcore.io.IoBridge.open(IoBridge.java:574)
                                                                                                          at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
                                                                                                          at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
                                                                                                          at androidx.media3.datasource.FileDataSource.openLocalFile(FileDataSource.java:186)
                                                                                                          at androidx.media3.datasource.FileDataSource.open(FileDataSource.java:116) 
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272) 
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029) 
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:417) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                          at java.lang.Thread.run(Thread.java:1012) 
                                                                                                      Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                          at libcore.io.Linux.open(Native Method)
                                                                                                          at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                          at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
                                                                                                          at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                          at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8165)
                                                                                                          at libcore.io.IoBridge.open(IoBridge.java:560)
                                                                                                          at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
                                                                                                          at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
                                                                                                          at androidx.media3.datasource.FileDataSource.openLocalFile(FileDataSource.java:186) 
                                                                                                          at androidx.media3.datasource.FileDataSource.open(FileDataSource.java:116) 
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272) 
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029) 
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:417) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                          at java.lang.Thread.run(Thread.java:1012) 
```

The stack trace has a helpful hint which may help us fix the issue: "Caused by: androidx.media3.datasource.FileDataSource$FileDataSourceException: uri has query and/or fragment, which are not supported. Did you call Uri.parse() on a string containing '?' or '#'? Use Uri.fromFile(new File(path)) to avoid this. path=/data/user/0/org.dharmaseed.android/files/downloads/ds_81433_What is Equanimity Anyway,query= And Is It Worth Cultivating? (Retreat at Spirit Rock).mp3,fragment=null"

**Comment by bb4242** [comment]
Fixed in #103.
