### ISSUE TITLE
App Not Responding (ANR) issues in production 

### ISSUE THREAD

**Issue by intermarc** [dharmaseed/dharmaseed-android#99]
The app currently has a high ANR rate in production. A corresponding issue was opened in the media3 library [here](https://github.com/androidx/media/issues/890).

The ANRs currently reported in the Google Play Console largely occur in the `PlayTalkActivity`:
 

>   at jdk.internal.misc.Unsafe.park (Native method)
>   at java.util.concurrent.locks.LockSupport.park (LockSupport.java:211)
>   at com.google.common.util.concurrent.AbstractFuture.get (AbstractFuture.java:557)
>   at org.dharmaseed.android.PlayTalkActivity.lambda$onResume$0$org-dharmaseed-android-PlayTalkActivity (PlayTalkActivity.java:192)
>   at org.dharmaseed.android.PlayTalkActivity$$ExternalSyntheticLambda0.run (unavailable:2)
>   at android.os.Handler.handleCallback (Handler.java:958)
>   at android.os.Handler.dispatchMessage (Handler.java:99)
>   at android.os.Looper.loopOnce (Looper.java:230)
>   at android.os.Looper.loop (Looper.java:319)
>   at android.app.ActivityThread.main (ActivityThread.java:8893)
>   at java.lang.reflect.Method.invoke (Native method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)

**Comment by intermarc** [comment]
I've discovered that I can reliably produce an ANR on one particular phone as follows:

https://github.com/dharmaseed/dharmaseed-android/assets/144038206/963b7281-d8ef-44f6-8395-b888cc14d7a7


These are the steps to reproduce the issue:

1. Start playing a talk
2. Pause the talk
3. Switch to the home screen
4. Dismiss the dharmaseed app
5. Press the play button in the notification (which no longer works!)
6. Press the notification area to get back to the PlayTalk activity

This is related to a [known issue](https://github.com/androidx/media/issues/805) in the media3 library: the notification no longer works as intended after the app is killed in the background.

The ANR message in the logs is not the same as the one seen in production, however:

> UnsupportedOperationException: Make sure to implement MediaSession.Callback.onPlaybackResumption() if you add a media button receiver to your manifest or if you implement the recent media item contract with your MediaLibraryService.
> java.lang.UnsupportedOperationException
> at androidx.media3.session.MediaSession$Callback.onPlaybackResumption(MediaSession.java:1491)
> at androidx.media3.session.MediaSessionImpl.handleMediaControllerPlayRequest(MediaSessionImpl.java:865)
> at androidx.media3.session.MediaSessionStub.lambda$playForControllerInfo$19$androidx-media3-session-MediaSessionStub(MediaSessionStub.java:727)
> at androidx.media3.session.MediaSessionStub$$ExternalSyntheticLambda29.accept(Unknown Source:6)
> at androidx.media3.session.MediaSessionStub.lambda$sendSessionResultSuccess$0(MediaSessionStub.java:158)
> at androidx.media3.session.MediaSessionStub$$ExternalSyntheticLambda25.run(Unknown Source:2)
> at androidx.media3.session.MediaSessionStub.lambda$sendSessionResultSuccess$1(MediaSessionStub.java:167)
> at androidx.media3.session.MediaSessionStub$$ExternalSyntheticLambda18.run(Unknown Source:2)
> ...

It is not clear whether this issue is related to the ANRs seen in production.

**Comment by intermarc** [comment]
The fixes suggested in the [open media3 issue](https://github.com/androidx/media/issues/890) do not help to prevent the  reproducible ANR detailed above.

**Comment by intermarc** [comment]
It looks like v1.6.2 has solved the ANR issue, so I will close this now.

I've opened a new issue for the broken media notification (#101).
